### ISSUE TITLE
[SOLVED] Init database process run infinitely

### ISSUE THREAD

**Issue by m0rfeo** [xtreme-d/docker-slurm-cluster#3]
Hi, i see on supervisorctl status that init database process run infinitely, but if i just do docker-compose up -d without modify anything its works, i really dont undestand that and  need some help

**Comment by hackprime** [comment]
Hi @kikegarcia28 

Definitely, at the first start of `docker-compose up -d` command, the "slurmdbd" process of `axc-headnode` container spends some time applying database migrations in MariaDB. While it's busy, you will see the following messages in the container logs repeated many times.
```
Waiting for database slurm_acct_db on mariadb...
ERROR 2003 (HY000): Can't connect to MySQL server on 'mariadb' (111)
Waiting for database slurm_acct_db on mariadb...
ERROR 2003 (HY000): Can't connect to MySQL server on 'mariadb' (111)
...
```
After that, the supervisor running `slurmdbd_init__oneshot` one time script, wrapped as a supervisor program, to fill initial data about the slurm cluster into empty MariaDB tables if it does not exist yet.

Could it be the answer to your questions?
If no, please provide more details about your issue.

**Comment by m0rfeo** [comment]
i did some changes on .env file and maybe something there make the process run infinitely, I just will try to modify and check all the parameters and if the error stay i will ask again here. Thanks for your attention and support!

**Comment by m0rfeo** [comment]
SOLVED. Just bad configuration
