### ISSUE TITLE
[SOLVED] Can't create query on database for Slurm in MariaDB Container

### ISSUE THREAD

**Issue by m0rfeo** [xtreme-d/docker-slurm-cluster#7]
Hi, trying to select on tables in slurm_acct_db i can create query from the tables and get the correct output.

But some tables have this format axc-docker-cluster_something_something and on this tables i recive error

see the following output when i try to do select * from axc-docker-cluster_assoc_table:

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-docker-cluster_assoc_table' at line 1

I think that the problem is this caracter (-) on MySQL.

**Comment by hackprime** [comment]
@m0rfeo Tables contain non-standard characters in their names so you need to wrap the table name in your request into backticks.
```sql
select * from `docker-slurm-cluster_assoc_table`;
```

**Comment by m0rfeo** [comment]
Thanks for the help!
